DROP TABLE IF EXISTS notes CASCADE;
CREATE TABLE notes (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL
);

DROP TABLE IF EXISTS noteshistory CASCADE;
CREATE TABLE noteshistory (
  notes_id INTEGER NOT NULL,
  version_id INTEGER NOT NULL,
  title VARCHAR(255) NOT NULL,
  text TEXT NOT NULL,
  date TIMESTAMP NOT NULL,
  PRIMARY KEY (notes_id, version_id)
);

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  reg_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
